var  wordList = [
  "Socrates",
  "Plato",
  "Aristotle",
  "René Descartes",
  "Immanuel Kant",
  "Friedrich Nietzsche",
  "Jean-Jacques Rousseau",
  "Thomas Hobbes",
  "John Locke",
  "David Hume",
  "Karl Marx",
  "Friedrich Engels",
  "John Stuart Mill",
  "Bertrand Russell",
  "Gottfried Wilhelm Leibniz",
  "Blaise Pascal",
  "Arthur Schopenhauer",
  "Hannah Arendt",
  "Michel Foucault",
  "Simone de Beauvoir",
  "Jean-Paul Sartre",
  "Albert Camus",
  "Ralph Waldo Emerson",
  "Henry David Thoreau",
  "Søren Kierkegaard",
  "Martin Heidegger",
  "Georg Wilhelm Friedrich Hegel",
  "Ludwig Wittgenstein",
  "William James",
  "George Berkeley",
  "Baruch Spinoza",
  "Auguste Comte",
  "Confucius",
  "Lao Tzu",
  "Fritjof Capra",
  "Michel de Montaigne",
  "John Dewey",
  "Ayn Rand",
  "Simone Weil",
  "Epictetus",
  "Seneca",
  "Heraclitus",
  "Parmenides",
  "Xenophanes",
  "Diogenes of Sinope",
  "Plotinus",
  "Thomas Aquinas",
  "Niccolò Machiavelli",
  "G. E. M. Anscombe",
  "Alfred North Whitehead",
  "C. S. Peirce",
  "John Rawls",
  "Peter Singer",
  "Judith Butler",
  "Slavoj Žižek",
  "Sigmund Freud",
  "Carl Jung",
  "Ernst Cassirer",
  "Maurice Merleau-Ponty",
  "Edmund Husserl",
  "Jacques Derrida",
  "Giorgio Agamben",
  "Alain Badiou",
  "Gilles Deleuze",
  "Alfred Jules Ayer",
  "Daniel Dennett",
  "John Searle",
  "Thomas Kuhn",
  "Paul Feyerabend",
  "Karl Popper",
  "Red Panda",
  "Red Wolf",
  "Red-Handed Tamarin",
  "Red-Tailed Monkey",
  "Red-Tailed Tropicbird",
  "Reindeer",
  "Reticulated Giraffe",
  "Rhesus Monkey",
  "Rim-Snouted Caiman",
  "Ring-Tailed Lemur",
  "Rock Hyrax",
  "Roe Deer",
  "Rufous Elephant Shrew",
  "Sable Antelope",
  "Sambar Deer",
  "Savanna Baboon",
  "Savanna Elephant",
  "Schomburgk's Deer",
  "Sea Otter",
  "Sei Whale",
  "Serval",
  "Short-Beaked Common Dolphin",
  "Siberian Tiger",
  "Silvery Marmoset",
  "Sloth",
  "Snow Leopard",
  "Southern Elephant Seal",
  "Southern Giraffe",
  "Southern Sea Otter",
  "Southern White Rhinoceros",
  "Spectacled Bear",
  "Spider Monkey",
  "Spotted Hyena",
  "Squirrel Monkey",
  "Steller Sea Lion",
  "Stoat",
  "Striped Dolphin",
  "Sumatran Elephant",
  "The Edge",
  "Slash",
  "Bono",
  "Freddie Mercury",
  "Mick Jagger",
  "David Bowie",
  "Elvis Presley",
  "Bruce Springsteen",
  "Kurt Cobain",
  "Axl Rose",
  "Johnny Rotten",
  "Jimmy Page",
  "Jim Morrison",
  "Janis Joplin",
  "Bob Dylan",
  "Steven Tyler",
  "Ozzy Osbourne",
  "Keith Richards",
  "Roger Waters",
  "Roger Daltrey",
  "Brian Wilson",
  "Eric Clapton",
  "Eddie Van Halen",
  "Alice Cooper",
  "Iggy Pop",
  "Bon Scott",
  "Robert Plant",
  "Billy Idol",
  "Tom Petty",
  "Gene Simmons",
  "Joan Jett",
  "Stevie Nicks",
  "Patti Smith",
  "Debbie Harry",
  "Joe Strummer",
  "Peter Gabriel",
  "Billy Joel",
  "Tommy Lee",
  "Phil Collins",
  "Annie Lennox",
  "Tina Turner",
  "Bryan Adams",
  "Ronnie Wood",
  "Billy Corgan",
  "Thom Yorke",
  "Chris Cornell",
  "Dave Grohl",
  "Eddie Vedder",
  "Kirk Hammett",
  "Noel Gallagher",
  "Liam Gallagher",
  "Dave Matthews",
  "Gwen Stefani",
  "Marilyn Manson",
  "Amy Lee",
  "Jack White",
  "Dave Mustaine",
  "Rob Zombie",
  "Trent Reznor",
  "Brandon Flowers",
  "Gerard Way",
  "Billie Joe Armstrong",
  "Dave Navarro",
  "Courtney Love",
  "Lenny Kravitz",
  "Serj Tankian",
  "Chester Bennington",
  "Corey Taylor",
  "Hayley Williams",
  "Florence Welch",
  "Jared Leto",
  "Alex Turner",
  "Josh Homme",
  "Dan Auerbach",
  "Julian Casablancas",
  "Win Butler",
  "Karen O",
  "Billy Gibbons",
  "Flea",
  "Anthony Kiedis",
  "Zakk Wylde",
  "Scott Weiland",
  "James Hetfield",
  "Eddie Vedder",
  "Mark Twain",
  "George Orwell",
  "Lewis Carroll",
  "Voltaire",
  "O. Henry",
  "J.K. Rowling",
  "Dr. Seuss",
  "George Eliot",
  "Charlotte Brontë",
  "Emily Brontë",
  "Anne Brontë",
  "H.P. Lovecraft",
  "Jane Austen",
  "Ernest Hemingway",
  "William Shakespeare",
  "Charles Dickens",
  "Agatha Christie",
  "J.R.R. Tolkien",
  "F. Scott Fitzgerald",
  "Leo Tolstoy",
  "Virginia Woolf",
  "Arthur Conan Doyle",
  "Harper Lee",
  "Roald Dahl",
  "Hermann Hesse",
  "Gabriel García Márquez",
  "Stephen King",
  "Edgar Allan Poe",
  "Ray Bradbury",
  "T.S. Eliot",
  "Pablo Neruda",
  "Miguel de Cervantes",
  "John Steinbeck",
  "Rudyard Kipling",
  "Emily Dickinson",
  "Oscar Wilde",
  "Anton Chekhov",
  "Franz Kafka",
  "Hans Christian Andersen",
  "Samuel Beckett",
  "William Faulkner",
  "Ralph Waldo Emerson",
  "Nathaniel Hawthorne",
  "Herman Melville",
  "Walt Whitman",
  "Dante Alighieri",
  "Victor Hugo",
  "Albert Camus",
  "Fyodor Dostoevsky",
  "Mikhail Bulgakov",
  "Sylvia Plath",
  "John Milton",
  "Robert Frost",
  "Jack Kerouac",
  "James Joyce",
  "Emily Brontë",
  "John Keats",
  "W.B. Yeats",
  "Langston Hughes",
  "Zora Neale Hurston",
  "Maya Angelou",
  "Stalin"
  // Add more names here...
];
